### ISSUE TITLE
Ujednolicenie jednolitych marginesów na stronie

### ISSUE THREAD

**Issue by bartoszziarnek** [Ariqu/covid-19-app#2]
Hej
Problem z marginesami u dołu 
![ss1](https://user-images.githubusercontent.com/7452647/79698976-a7c59e80-828c-11ea-93a2-3c71f9fb0ad7.png)
aplikacji.

**Comment by Ariqu** [comment]
Błąd został poprawiony.
- Marginesy zostały wyrównane na: 0;
- Padding dolny został również wyrównany na 0;

Ostylowanie "iframe" takimi skryptami w style.css skutkowały poprawieniem błedu opsanego przez pana.
